version: '3.0'
services:
   clang-libcpp-boost-env:
      image: shri314/clang-libcpp-boost
      entrypoint: sleep infinity
      restart: always
      volumes:
         - .:/src
      privileged: true
